In [26]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [3]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [12]:
train_df.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,1,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,1,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,1,1,0,1,1,0,1,0,1,0
5,31295,31295,6500.0,0.1614,228.98,65000.0,27.49,1.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
6,173238,173238,40000.0,0.1240,897.89,171000.0,20.74,0.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
7,116755,116755,5000.0,0.1719,178.74,55000.0,10.80,1.0,0.0,5.0,...,1,1,0,1,1,0,1,0,1,0
8,170311,170311,6000.0,0.1102,196.49,36000.0,27.28,0.0,0.0,19.0,...,1,1,0,1,1,0,1,0,1,0
9,254794,254794,10625.0,0.1102,347.95,73000.0,7.09,0.0,2.0,18.0,...,1,1,0,1,1,0,1,0,1,0

In [ ]:
train

In [13]:
# Convert categorical data to numeric and separate target feature for training data
train_df = pd.get_dummies(train_df)

In [14]:
# Convert categorical data to numeric and separate target feature for testing data
test_df = pd.get_dummies(test_df)

In [15]:
X = train_df.drop(['loan_status_low_risk'], axis=1)
y = train_df['loan_status_low_risk']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
# Train the Logistic Regression model on the unscaled data and print the model score
evaluator = LogisticRegression()
evaluator

LogisticRegression()

In [22]:
evaluator.fit(X_train, y_train)

C:\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [24]:
print(f"Training Data Score: {evaluator.score(X_train, y_train)}")
print(f"Testing Data Score: {evaluator.score(X_test, y_test)}")

Training Data Score: 0.6524356869184456
Testing Data Score: 0.6466338259441707

In [27]:
# Train a Random Forest Classifier model and print the model score
clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train, y_train)
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test, y_test)}')

Training Score: 1.0
Testing Score: 0.999671592775041